-- INSERT INTO diseases (id, name, description, symptoms, causes, preventions, treatment) VALUES 
-- ('D001', 'Cảm lạnh thông thường', 'Cảm lạnh là một bệnh nhiễm trùng đường hô hấp trên do vi khuẩn gây ra.', 'Hắt hơi, sổ mũi, đau họng, ho, mệt mỏi.', 'Virus cảm lạnh lây lan qua tiếp xúc trực tiếp hoặc gián tiếp với người bệnh.', 'Rửa tay thường xuyên, tránh tiếp xúc gần với người bệnh, duy trì hệ miễn dịch khỏe mạnh.', 'Nghỉ ngơi, uống nhiều nước, sử dụng thuốc giảm triệu chứng như thuốc giảm đau và hạ sốt.'),
-- ('D002', 'Cảm cúm', 'Bệnh nhiễm trùng đường hô hấp cấp tính do virus cúm (Influenza) gây ra, thường nặng hơn cảm lạnh.', 'Sốt cao đột ngột (thường trên 38.5°C), ớn lạnh, đau đầu dữ dội, đau mỏi cơ bắp nghiêm trọng, mệt mỏi kiệt sức, ho khan, đau họng.', 'Virus cúm nhóm A, B, C. Lây truyền qua giọt bắn đường hô hấp khi người bệnh ho, hắt hơi hoặc nói chuyện.', 'Tiêm vắc-xin phòng cúm hàng năm, rửa tay thường xuyên bằng xà phòng, che miệng khi ho/hắt hơi, tránh tụ tập nơi đông người khi có dịch.', 'Nghỉ ngơi, uống nhiều nước/chất điện giải. Dùng thuốc hạ sốt (Paracetamol, Ibuprofen). Bác sĩ có thể chỉ định thuốc kháng virus (như Oseltamivir) trong một số trường hợp.'),
-- ('D003', 'Viêm họng và Viêm Amidan cấp', 'Tình trạng viêm, sưng, tấy đỏ ở niêm mạc họng và/hoặc amidan, gây đau rát.', 'Đau họng, rát họng, khó nuốt, amidan sưng đỏ (có thể có mủ trắng), sốt, sưng hạch cổ, hôi miệng.', 'Chủ yếu do virus (như virus cảm lạnh, cúm). Một số trường hợp do vi khuẩn (phổ biến là liên cầu khuẩn nhóm A - Streptococcus pyogenes).', 'Vệ sinh răng miệng sạch sẽ, súc họng bằng nước muối ấm, giữ ấm vùng cổ, rửa tay thường xuyên, tránh khói thuốc lá.', 'Uống nhiều nước ấm, súc họng nước muối. Dùng thuốc giảm đau, hạ sốt. Nếu nguyên nhân là vi khuẩn, bác sĩ sẽ kê đơn kháng sinh.'),
-- ('D004', 'Viêm phế quản cấp', 'Tình trạng viêm nhiễm cấp tính của niêm mạc phế quản (đường dẫn khí lớn vào phổi), thường xảy ra sau một đợt cảm lạnh hoặc cúm.', 'Ho (thường là ho có đờm, đờm có thể màu trắng, vàng hoặc xanh), tức ngực, mệt mỏi, khó thở nhẹ, sốt nhẹ.', 'Hầu hết do virus (tương tự virus gây cảm lạnh, cúm). Một số ít do vi khuẩn hoặc hít phải chất kích ứng (khói thuốc, bụi, ô nhiễm).', 'Không hút thuốc lá, tránh xa khói thuốc và môi trường ô nhiễm, tiêm vắc-xin cúm hàng năm, rửa tay thường xuyên.', 'Nghỉ ngơi, uống nhiều nước. Dùng thuốc giảm ho (nếu ho khan gây khó chịu), thuốc long đờm. Máy tạo độ ẩm có thể giúp. Kháng sinh thường không cần thiết (trừ khi do vi khuẩn).'),
-- ('D005', 'Bệnh Lao phổi', 'Bệnh truyền nhiễm do vi khuẩn Mycobacterium tuberculosis (M. tuberculosis) gây ra, chủ yếu tấn công phổi nhưng có thể ảnh hưởng đến các bộ phận khác.', 'Ho kéo dài (trên 2 tuần), ho ra máu, đau ngực, sốt về chiều, đổ mồ hôi đêm, sụt cân không rõ nguyên nhân, mệt mỏi.', 'Vi khuẩn M. tuberculosis lây truyền qua không khí khi người bệnh lao phổi ho, hắt hơi, khạc nhổ.', 'Tiêm vắc-xin BCG cho trẻ sơ sinh, che miệng khi ho/hắt hơi, đảm bảo môi trường sống thông thoáng, phát hiện và điều trị sớm cho người bệnh.', 'Điều trị bằng phác đồ kháng sinh đặc hiệu (thường kéo dài từ 6 tháng trở lên) theo đúng chỉ định và hướng dẫn của bác sĩ.'),
-- ('D006', 'Sốt xuất huyết', 'Bệnh truyền nhiễm cấp tính do virus Dengue gây ra, lây truyền qua muỗi vằn (Aedes aegypti).', 'Sốt cao đột ngột (39-40°C) kéo dài 2-7 ngày, đau đầu dữ dội, đau nhức hốc mắt, đau cơ khớp. Có thể xuất hiện chấm xuất huyết dưới da, chảy máu cam, chảy máu chân răng.', 'Virus Dengue (có 4 type huyết thanh: DEN-1, DEN-2, DEN-3, DEN-4) do muỗi vằn đốt người bệnh rồi truyền virus sang người lành.', 'Diệt muỗi, lăng quăng (bọ gậy); ngủ màn (kể cả ban ngày); mặc quần áo dài tay; dọn dẹp nơi nước đọng quanh nhà; dùng kem chống muỗi.', 'Không có thuốc điều trị đặc hiệu. Chủ yếu là điều trị triệu chứng: hạ sốt bằng Paracetamol (tuyệt đối không dùng Aspirin, Ibuprofen), uống nhiều nước (Oresol), theo dõi dấu hiệu cảnh báo.'),
-- ('D007', 'Sốt rét', 'Bệnh truyền nhiễm do ký sinh trùng Plasmodium gây ra, lây truyền qua vết đốt của muỗi Anopheles.', 'Sốt rét điển hình qua 3 giai đoạn: Rét run (ớn lạnh, run bần bật), Sốt cao (40-41°C, mặt đỏ, da khô), Vã mồ hôi (sốt giảm, mồ hôi ra nhiều). Cơn sốt có tính chu kỳ.', 'Ký sinh trùng Plasmodium (P. falciparum, P. vivax, P. malariae, P. ovale) do muỗi Anopheles truyền vào máu.', 'Ngủ màn tẩm hóa chất diệt muỗi, dùng kem xua muỗi, mặc quần áo che chắn, diệt muỗi và bọ gậy, uống thuốc phòng ngừa khi vào vùng sốt rét.', 'Sử dụng thuốc đặc trị sốt rét (như Artemisinin, Chloroquine...) theo phác đồ của Bộ Y tế.'),
-- ('D008', 'Bệnh Tay Chân Miệng', 'Bệnh truyền nhiễm cấp tính do virus đường ruột gây ra, thường gặp ở trẻ em dưới 5 tuổi.', 'Sốt (nhẹ hoặc cao), đau họng, biếng ăn. Xuất hiện các bọng nước/vết loét ở niêm mạc miệng. Phát ban dạng phỏng nước ở lòng bàn tay, lòng bàn chân, đầu gối, mông.', 'Virus Enterovirus, phổ biến nhất là Coxsackievirus A16 và Enterovirus 71 (EV71). Lây qua đường tiêu hóa (tiếp xúc phân, dịch tiết) hoặc giọt bắn hô hấp.', 'Rửa tay thường xuyên cho trẻ và người chăm sóc. Vệ sinh đồ chơi, vật dụng. Không cho trẻ mút tay, bốc thức ăn. Cách ly trẻ bệnh tại nhà.', 'Không có thuốc đặc trị. Điều trị triệu chứng: hạ sốt, dùng thuốc bôi giảm đau rát, uống nhiều nước mát, ăn thức ăn mềm, lỏng. Theo dõi biến chứng.'),
-- ('D009', 'Viêm Kết Mạc (Đau mắt đỏ)', 'Tình trạng viêm lớp màng trong suốt (kết mạc) bao phủ lòng trắng của mắt và mặt trong của mí mắt.', 'Mắt đỏ, cộm, ngứa, chảy nước mắt, có nhiều ghèn (dử mắt) màu vàng hoặc xanh (do vi khuẩn) hoặc trong, dính (do virus), nhạy cảm với ánh sáng, mí mắt sưng.', 'Virus (phổ biến nhất, rất dễ lây), vi khuẩn, hoặc dị ứng (phấn hoa, lông động vật, bụi).', 'Rửa tay thường xuyên, không dụi mắt, không dùng chung khăn mặt/đồ trang điểm mắt, tránh tiếp xúc gần với người bệnh, đeo kính bảo vệ khi ra ngoài.', 'Vệ sinh mắt bằng nước muối sinh lý. Nếu do virus, bệnh tự khỏi. Nếu do vi khuẩn, bác sĩ kê thuốc nhỏ mắt kháng sinh. Nếu do dị ứng, dùng thuốc chống dị ứng.'),
-- ('D010', 'Bệnh Tiêu chảy cấp', 'Tình trạng đi ngoài phân lỏng hoặc tóe nước từ 3 lần trở lên trong 24 giờ, kéo dài không quá 14 ngày.', 'Đi ngoài phân lỏng nhiều lần, đau quặn bụng, nôn, sốt, mệt mỏi. Nguy cơ chính là mất nước và điện giải (khát nước, môi khô, mắt trũng, mệt lả).', 'Nhiễm trùng (virus như Rotavirus, vi khuẩn như E. coli, tả, lỵ) do ăn uống không hợp vệ sinh. Một số trường hợp do thuốc hoặc không dung nạp thực phẩm.', 'Ăn chín uống sôi, rửa tay trước khi ăn và sau khi đi vệ sinh, sử dụng nguồn nước sạch, xử lý phân an toàn, tiêm vắc-xin (Rotavirus, tả).', 'Quan trọng nhất là bù nước và điện giải (uống Oresol). Tiếp tục cho ăn (ăn thức ăn lỏng, dễ tiêu). Dùng thuốc theo chỉ định của bác sĩ.'),
-- ('D011', 'Viêm dạ dày ruột', 'Tình trạng viêm nhiễm ở niêm mạc dạ dày và ruột non, thường gọi là ''ngộ độc thực phẩm'' hoặc ''cúm dạ dày''.', 'Nôn, buồn nôn, tiêu chảy (thường đột ngột), đau quặn bụng, có thể kèm sốt, ớn lạnh, mệt mỏi.', 'Thường do virus (Norovirus, Rotavirus) hoặc vi khuẩn (Salmonella, E. coli, Campylobacter) từ thực phẩm hoặc nước uống bị ô nhiễm.', 'Rửa tay kỹ, bảo quản và chế biến thực phẩm an toàn (ăn chín, uống sôi, tách riêng đồ sống và chín).', 'Bệnh thường tự khỏi. Quan trọng là bù nước và điện giải (Oresol) để tránh mất nước. Nghỉ ngơi. Ăn thức ăn nhạt, dễ tiêu (cháo, bánh mì nướng) khi triệu chứng thuyên giảm.'),
-- ('D012', 'Thủy đậu', 'Bệnh truyền nhiễm cấp tính do virus Varicella-Zoster (VZV) gây ra, rất dễ lây lan.', 'Sốt nhẹ, mệt mỏi, chán ăn. Sau đó xuất hiện phát ban (nốt rạ): nốt đỏ -> nốt phỏng nước (rất ngứa) -> vỡ, đóng vảy. Mọc toàn thân.', 'Virus Varicella-Zoster. Lây qua đường hô hấp (giọt bắn) hoặc tiếp xúc trực tiếp với dịch từ nốt phỏng nước.', 'Tiêm vắc-xin phòng thủy đậu (biện pháp hiệu quả nhất). Cách ly người bệnh, tránh tiếp xúc với dịch từ nốt phỏng.', 'Điều trị triệu chứng: hạ sốt (Paracetamol), bôi dung dịch sát khuẩn (xanh methylen) lên nốt phỏng vỡ, giữ vệ sinh da, cắt móng tay (tránh gãi gây bội nhiễm).'),
-- ('D013', 'Bệnh Tăng huyết áp', 'Tình trạng áp lực của máu tác động lên thành động mạch cao hơn mức bình thường một cách mạn tính. (Chỉ số huyết áp >= 140/90 mmHg).', 'Thường không có triệu chứng rõ ràng (nên gọi là ''kẻ giết người thầm lặng''). Một số người có thể bị đau đầu, chóng mặt, ù tai, hoa mắt, chảy máu cam.', 'Hầu hết là vô căn (nguyên phát). Yếu tố nguy cơ: tuổi tác, di truyền, thừa cân, béo phì, ăn mặn, hút thuốc lá, uống nhiều rượu bia, stress, lười vận động.', 'Duy trì cân nặng lý tưởng, chế độ ăn uống lành mạnh (giảm muối, tăng rau xanh), tập thể dục đều đặn, không hút thuốc, hạn chế rượu bia, kiểm soát căng thẳng.', 'Thay đổi lối sống. Dùng thuốc hạ huyết áp theo chỉ định của bác sĩ (thuốc lợi tiểu, chẹn beta, ức chế men chuyển...). Theo dõi huyết áp thường xuyên.'),
-- ('D014', 'Bệnh Tim mạch vành', 'Bệnh lý xảy ra khi các động mạch vành (mạch máu nuôi tim) bị hẹp hoặc tắc nghẽn, thường do mảng xơ vữa, làm giảm lưu lượng máu đến cơ tim.', 'Đau thắt ngực (cảm giác đè nén, siết chặt ở ngực, có thể lan ra cánh tay, vai, cổ), khó thở, mệt mỏi, tim đập nhanh. Nặng nhất là nhồi máu cơ tim.', 'Xơ vữa động mạch (mảng bám cholesterol tích tụ). Yếu tố nguy cơ: tăng huyết áp, rối loạn mỡ máu (cao Cholesterol), đái tháo đường, hút thuốc, béo phì.', 'Kiểm soát tốt huyết áp, mỡ máu, đường huyết. Chế độ ăn lành mạnh (ít béo bão hòa, ít muối), không hút thuốc, tập thể dục, duy trì cân nặng hợp lý.', 'Thay đổi lối sống. Dùng thuốc (giãn mạch, giảm mỡ máu, chống đông máu). Can thiệp (nong mạch, đặt stent) hoặc phẫu thuật bắc cầu động mạch vành nếu cần.'),
-- ('D015', 'Đái tháo đường', 'Bệnh rối loạn chuyển hóa mạn tính, đặc trưng bởi mức đường (glucose) trong máu luôn cao hơn bình thường.', '(Type 2 thường âm thầm) Cổ điển (Type 1): Ăn nhiều, uống nhiều, tiểu nhiều, gầy sút cân nhanh. Mệt mỏi, mờ mắt, vết thương lâu lành, nhiễm trùng da.', 'Type 1: Tuyến tụy không sản xuất insulin (thường do tự miễn). Type 2: Cơ thể kháng insulin hoặc sản xuất không đủ insulin (liên quan lối sống, béo phì).', '(Type 2) Duy trì cân nặng hợp lý, chế độ ăn lành mạnh (giảm đường, tinh bột, tăng chất xơ), tập thể dục thường xuyên, không hút thuốc.', '(Type 1) Tiêm insulin. (Type 2) Thay đổi lối sống, dùng thuốc uống hạ đường huyết, có thể cần tiêm insulin. Cần theo dõi đường huyết và khám định kỳ.'),
-- ('D016', 'Ung thư', 'Nhóm bệnh lý đặc trưng bởi sự phát triển không kiểm soát của các tế bào bất thường, chúng xâm lấn và phá hủy các mô cơ thể, và có thể di căn.', 'Rất đa dạng. Dấu hiệu cảnh báo chung: sụt cân không rõ nguyên nhân, mệt mỏi, sốt kéo dài, thay đổi thói quen đại/tiểu tiện, vết loét không lành, ho dai dẳng, xuất huyết bất thường, nổi u cục.', 'Đột biến gen trong tế bào. Yếu tố nguy cơ: di truyền, hút thuốc, uống rượu, phơi nhiễm hóa chất/bức xạ, nhiễm trùng (HPV, viêm gan B, C), béo phì.', 'Không hút thuốc, hạn chế rượu bia, ăn uống lành mạnh, tập thể dục, duy trì cân nặng, tiêm vắc-xin (HPV, viêm gan B), tránh nắng gắt, tầm soát ung thư định kỳ.', 'Tùy loại và giai đoạn. Các phương pháp chính: Phẫu thuật (loại bỏ khối u), Xạ trị (dùng tia X tiêu diệt tế bào ung thư), Hóa trị (dùng thuốc), Liệu pháp miễn dịch.'),
-- ('D017', 'Bệnh Phổi tắc nghẽn mạn tính (COPD)', 'Bệnh lý hô hấp mạn tính đặc trưng bởi sự tắc nghẽn luồng khí thở ra không hồi phục hoàn toàn, thường do viêm phế quản mạn và khí phế thũng.', 'Khó thở (nhất là khi gắng sức), ho mạn tính, khạc đờm mạn tính, thở khò khè, mệt mỏi, sụt cân (giai đoạn muộn).', 'Hút thuốc lá (kể cả thụ động) là nguyên nhân hàng đầu. Phơi nhiễm khói bụi, ô nhiễm không khí, hóa chất nghề nghiệp.', 'Ngưng hút thuốc lá tuyệt đối. Tránh xa môi trường khói bụi, ô nhiễm. Tiêm vắc-xin cúm và phế cầu hàng năm.', 'Không thể chữa khỏi. Bỏ hút thuốc. Dùng thuốc giãn phế quản (dạng hít/xịt), thuốc kháng viêm (corticosteroid dạng hít), liệu pháp oxy, phục hồi chức năng hô hấp.'),
-- ('D018', 'Viêm loét dạ dày và Tá tràng', 'Tình trạng niêm mạc dạ dày hoặc tá tràng (phần đầu ruột non) bị tổn thương, hình thành các vết loét do acid và men tiêu hóa (pepsin) gây ra.', 'Đau bụng vùng thượng vị (có thể đau âm ỉ hoặc quặn, đau khi đói hoặc sau khi ăn), ợ hơi, ợ chua, buồn nôn, nôn, đầy bụng, khó tiêu. Biến chứng: xuất huyết tiêu hóa, thủng.', 'Nhiễm vi khuẩn Helicobacter pylori (HP) là nguyên nhân chính. Lạm dụng thuốc kháng viêm không steroid (NSAIDs như Aspirin, Ibuprofen). Stress, rượu bia, thuốc lá.', 'Vệ sinh ăn uống (phòng lây nhiễm HP), sử dụng thuốc NSAIDs thận trọng, hạn chế rượu bia, thuốc lá, giảm căng thẳng.', 'Dùng thuốc giảm tiết acid (PPI), thuốc kháng sinh (nếu có HP), thuốc trung hòa acid (antacid). Thay đổi lối sống: ăn uống đúng giờ, tránh đồ chua cay, rượu bia.'),
-- ('D019', 'Bệnh Gút (Gout)', 'Bệnh viêm khớp do rối loạn chuyển hóa acid uric, làm nồng độ acid uric trong máu tăng cao, dẫn đến lắng đọng tinh thể urat ở khớp và các mô.', 'Cơn Gút cấp: Sưng, nóng, đỏ, đau dữ dội (thường ở khớp ngón chân cái), khởi phát đột ngột. Giai đoạn mạn: xuất hiện hạt tophi (cục u) dưới da, viêm khớp mạn tính.', 'Tăng sản xuất hoặc giảm đào thải acid uric. Yếu tố nguy cơ: Di truyền, nam giới, tuổi tác, béo phì, uống nhiều rượu bia, ăn nhiều thực phẩm giàu purin (nội tạng, hải sản, thịt đỏ).', 'Chế độ ăn uống hạn chế purin, hạn chế rượu bia (đặc biệt là bia), uống nhiều nước, duy trì cân nặng hợp lý, tập thể dục.', '(Cơn cấp) Thuốc kháng viêm (NSAIDs, Colchicine, Corticosteroid). (Mạn tính) Thuốc hạ acid uric máu (Allopurinol, Febuxostat) kết hợp thay đổi lối sống.'),
-- ('D020', 'Viêm khớp mạn tính', 'Thuật ngữ chung chỉ tình trạng viêm kéo dài ở một hoặc nhiều khớp. Hai loại phổ biến là Thoái hóa khớp (OA) và Viêm khớp dạng thấp (RA).', 'Đau khớp (tăng khi vận động - OA; đau cả khi nghỉ, cứng khớp buổi sáng - RA), sưng khớp, cứng khớp, giảm biên độ vận động, biến dạng khớp (giai đoạn muộn).', '(OA) Mòn sụn khớp do tuổi tác, chấn thương, béo phì. (RA) Rối loạn tự miễn (hệ miễn dịch tự tấn công màng hoạt dịch khớp).', 'Duy trì cân nặng lý tưởng, tập thể dục hợp lý (tránh chấn thương), chế độ ăn chống viêm (giàu omega-3, rau xanh), không hút thuốc.', 'Không chữa khỏi. Điều trị giảm đau, kháng viêm (NSAIDs, Corticoid), vật lý trị liệu. (RA) cần dùng thuốc điều trị cơ bản (DMARDs). Phẫu thuật (thay khớp) khi khớp hỏng nặng.');



INSERT INTO diseases (id, name, description, symptoms, causes, preventions, treatment) VALUES
('D001', 'Cảm lạnh thông thường',
'Cảm lạnh thông thường là bệnh nhiễm trùng đường hô hấp trên phổ biến, do virus gây ra, chủ yếu ảnh hưởng đến mũi và họng, thường lành tính nhưng có thể gây khó chịu. Bệnh thường xảy ra quanh năm, đặc biệt vào mùa lạnh, thời tiết chuyển mùa, hoặc khi cơ thể suy yếu.',
'Hắt hơi liên tục, sổ mũi, nghẹt mũi, đau rát họng, ho nhẹ, mệt mỏi, chán ăn, đau đầu nhẹ, nước mũi trong hoặc đặc dần, cảm giác ớn lạnh nhẹ.',
'Do nhiều loại virus (thường là Rhinovirus, Coronavirus, Adenovirus, RSV). Lây truyền chủ yếu qua giọt bắn từ người bệnh khi ho, hắt hơi, nói chuyện hoặc tiếp xúc với bề mặt nhiễm virus.',
'Rửa tay thường xuyên, tránh chạm tay lên mặt, che miệng khi ho/hắt hơi, duy trì dinh dưỡng và giấc ngủ đầy đủ, giữ ấm cơ thể, tránh tiếp xúc gần người bệnh.',
'Nghỉ ngơi tại nhà, uống nhiều nước, bổ sung vitamin C. Dùng thuốc giảm triệu chứng như hạ sốt, giảm đau, thuốc xịt mũi hoặc siro ho nếu cần. Hầu hết bệnh tự khỏi sau 5-7 ngày. Tránh dùng kháng sinh nếu không có nhiễm trùng thứ phát.'),

('D002', 'Cảm cúm',
'Cảm cúm là bệnh nhiễm trùng đường hô hấp cấp tính do virus cúm (Influenza) gây ra, có thể biến chứng nghiêm trọng ở người già, trẻ em và người có bệnh nền. Bệnh lây lan nhanh qua không khí và tiếp xúc gần.',
'Sốt cao đột ngột (thường trên 38.5°C), ớn lạnh, đau đầu dữ dội, đau mỏi cơ, đau khớp, mệt mỏi kiệt sức, ho khan, đau họng, chảy nước mũi, mất khẩu vị, nhức mắt, sổ mũi, chán ăn.',
'Virus cúm nhóm A, B, C. Lây qua giọt bắn đường hô hấp khi người bệnh ho, hắt hơi hoặc nói chuyện, hoặc tiếp xúc với đồ vật nhiễm virus.',
'Tiêm phòng vắc-xin cúm hàng năm, rửa tay thường xuyên bằng xà phòng, che miệng khi ho/hắt hơi, tránh tụ tập nơi đông người khi có dịch cúm, giữ ấm cơ thể, tăng cường dinh dưỡng và tập thể dục.',
'Nghỉ ngơi, uống nhiều nước/chất điện giải. Dùng thuốc hạ sốt, giảm đau (Paracetamol, Ibuprofen). Trong một số trường hợp nặng hoặc nguy cơ biến chứng cao, bác sĩ có thể chỉ định thuốc kháng virus (Oseltamivir, Zanamivir). Theo dõi biến chứng như viêm phổi.'),

('D003', 'Viêm họng và Viêm Amidan cấp',
'Viêm họng và viêm amidan cấp là tình trạng viêm, sưng, tấy đỏ ở niêm mạc họng và amidan, gây đau rát và khó chịu. Bệnh thường gặp ở trẻ em và thanh thiếu niên, có thể tái phát nhiều lần nếu điều trị không đầy đủ.',
'Đau rát họng, khó nuốt, nuốt đau, amidan sưng đỏ, có mủ trắng hoặc đốm vàng, sốt từ nhẹ đến cao, sưng hạch cổ, hôi miệng, ho khan, mệt mỏi, cảm giác cơ thể yếu.',
'Nguyên nhân chủ yếu do virus (Rhinovirus, Adenovirus, Influenza). Một số trường hợp do vi khuẩn (chủ yếu là Streptococcus pyogenes - liên cầu khuẩn nhóm A).',
'Vệ sinh răng miệng tốt, súc họng bằng nước muối ấm, tránh tiếp xúc gần với người bệnh, giữ ấm vùng cổ, rửa tay thường xuyên, tránh hút thuốc lá và môi trường ô nhiễm.',
'Uống nhiều nước, súc họng bằng nước muối, dùng thuốc giảm đau và hạ sốt. Nếu nguyên nhân là vi khuẩn, bác sĩ sẽ kê kháng sinh phù hợp. Nghỉ ngơi đầy đủ, ăn thức ăn mềm, tránh cay nóng.'),

('D004', 'Viêm phế quản cấp',
'Viêm phế quản cấp là tình trạng viêm nhiễm niêm mạc phế quản, thường xảy ra sau đợt cảm lạnh hoặc cúm, gây ho và khó thở. Bệnh thường tự khỏi trong vài tuần nhưng cần chăm sóc để tránh biến chứng.',
'Ho nhiều (có đờm trong, vàng, xanh hoặc trắng), tức ngực, khó thở nhẹ, mệt mỏi, sốt nhẹ, đau họng, cảm giác nặng ngực khi thở sâu.',
'Nguyên nhân chủ yếu do virus (tương tự virus cảm lạnh, cúm). Một số ít trường hợp do vi khuẩn (Mycoplasma, Streptococcus) hoặc tiếp xúc với khói, bụi, chất kích thích.',
'Không hút thuốc lá, tránh khói bụi và môi trường ô nhiễm, rửa tay thường xuyên, tiêm phòng cúm hàng năm, giữ ấm cơ thể.',
'Nghỉ ngơi, uống nhiều nước, dùng thuốc giảm ho, long đờm. Máy tạo độ ẩm không khí có thể giúp giảm kích ứng phế quản. Kháng sinh chỉ dùng nếu xác định vi khuẩn gây bệnh.'),

('D005', 'Bệnh Lao phổi',
'Lao phổi là bệnh truyền nhiễm nghiêm trọng do vi khuẩn Mycobacterium tuberculosis tấn công phổi và có thể lan ra các cơ quan khác. Bệnh tiến triển chậm, dễ trở thành mãn tính nếu không điều trị đúng cách.',
'Ho kéo dài trên 2 tuần, ho ra máu hoặc đờm lẫn máu, đau ngực, sốt nhẹ vào buổi chiều, đổ mồ hôi ban đêm, sụt cân không rõ nguyên nhân, mệt mỏi, khó thở khi gắng sức.',
'Vi khuẩn M. tuberculosis lây truyền qua không khí khi người bệnh ho, hắt hơi, khạc nhổ.',
'Tiêm vắc-xin BCG cho trẻ sơ sinh, che miệng khi ho/hắt hơi, đảm bảo thông thoáng nơi ở, tránh tiếp xúc với người bệnh chưa điều trị, phát hiện và điều trị sớm người nhiễm.',
'Điều trị theo phác đồ kháng sinh đặc hiệu (Isoniazid, Rifampicin, Pyrazinamide, Ethambutol) kéo dài ít nhất 6 tháng. Theo dõi định kỳ, đảm bảo tuân thủ thuốc để tránh kháng thuốc.'),

('D006', 'Sốt xuất huyết',
'Sốt xuất huyết là bệnh truyền nhiễm cấp tính do virus Dengue gây ra, lây truyền qua muỗi vằn Aedes aegypti. Bệnh có thể từ nhẹ đến nặng, nguy cơ tử vong cao nếu biến chứng thành sốc Dengue.',
'Sốt cao đột ngột 39-40°C, đau đầu dữ dội, đau nhức hốc mắt, đau cơ và khớp, chán ăn, buồn nôn, xuất hiện chấm xuất huyết dưới da, chảy máu cam, chảy máu chân răng, mệt mỏi.',
'Virus Dengue 4 type (DEN-1,2,3,4), lây từ muỗi vằn đốt người bệnh sang người lành.',
'Diệt muỗi và bọ gậy, ngủ màn, mặc quần áo dài, dọn dẹp nơi đọng nước quanh nhà, dùng kem chống muỗi, tránh bị muỗi đốt.',
'Không có thuốc đặc hiệu. Điều trị triệu chứng: hạ sốt bằng Paracetamol, uống nhiều nước/chất điện giải, theo dõi dấu hiệu cảnh báo (xuất huyết nặng, đau bụng, mệt lả) và nhập viện nếu cần.'),

('D007', 'Sốt rét',
'Sốt rét là bệnh truyền nhiễm do ký sinh trùng Plasmodium gây ra, lây truyền qua muỗi Anopheles. Bệnh có thể cấp tính hoặc mạn tính, gây biến chứng nặng nếu không điều trị kịp thời.',
'Sốt theo cơn chu kỳ: rét run, sốt cao 40-41°C, vã mồ hôi. Kèm ớn lạnh, đau đầu, đau cơ, mệt mỏi, buồn nôn, nôn, vàng da (trong trường hợp nặng), thiếu máu.',
'Ký sinh trùng Plasmodium (P. falciparum, P. vivax, P. malariae, P. ovale) do muỗi Anopheles truyền vào máu.',
'Ngủ màn tẩm hóa chất diệt muỗi, dùng kem xua muỗi, mặc quần áo che chắn, diệt muỗi và bọ gậy, uống thuốc phòng ngừa khi vào vùng có sốt rét.',
'Điều trị đặc hiệu bằng thuốc chống sốt rét (Artemisinin phối hợp, Chloroquine, Mefloquine...) theo phác đồ y tế. Theo dõi biến chứng như thiếu máu, suy đa tạng nếu nặng.'),

('D008', 'Bệnh Tay Chân Miệng',
'Bệnh Tay Chân Miệng (Hand, Foot, and Mouth Disease - HFMD) là bệnh truyền nhiễm cấp tính do virus đường ruột (Enterovirus) gây ra, thường gặp ở trẻ dưới 5 tuổi. Bệnh lây nhanh qua tiếp xúc trực tiếp với dịch tiết từ mụn nước, phân hoặc nước mũi của người bệnh.',
'Sốt nhẹ hoặc cao, đau họng, biếng ăn, nổi các bọng nước/vết loét trong miệng, phát ban phỏng nước ở lòng bàn tay, lòng bàn chân, đầu gối, mông. Trẻ có thể quấy khóc, mệt mỏi, khó chịu, bỏ bú/ăn.',
'Virus Enterovirus, phổ biến Coxsackievirus A16 và Enterovirus 71. Lây qua đường tiêu hóa (phân-miệng) hoặc hô hấp (giọt bắn).',
'Rửa tay thường xuyên, vệ sinh đồ chơi, vật dụng, không cho trẻ mút tay hay bốc thức ăn, cách ly trẻ bệnh tại nhà, tránh tụ tập đông người.',
'Không có thuốc đặc hiệu. Điều trị triệu chứng: hạ sốt, bôi thuốc giảm đau rát, uống nhiều nước, ăn thức ăn mềm/lỏng. Theo dõi biến chứng thần kinh hoặc tim mạch nếu EV71 gây ra. Nghỉ ngơi và theo dõi trẻ sát sao.'),

('D009', 'Viêm Kết Mạc (Đau mắt đỏ)',
'Viêm kết mạc là tình trạng viêm lớp màng trong suốt bao phủ lòng trắng mắt và mặt trong mí mắt, gây đỏ mắt, khó chịu, và có thể lây nhiễm. Bệnh có thể do virus, vi khuẩn hoặc dị ứng.',
'Mắt đỏ, cộm, ngứa, chảy nước mắt, xuất hiện ghèn màu vàng/xanh (vi khuẩn) hoặc trong dính (virus), nhạy cảm ánh sáng, sưng mí, mệt mỏi nhẹ nếu kèm nhiễm trùng.',
'Nguyên nhân: virus (Adenovirus phổ biến), vi khuẩn (Staphylococcus, Streptococcus), dị ứng (phấn hoa, lông động vật, bụi). Lây qua tiếp xúc trực tiếp hoặc đồ dùng cá nhân.',
'Rửa tay thường xuyên, không dụi mắt, không dùng chung khăn mặt/đồ trang điểm mắt, tránh tiếp xúc gần người bệnh, đeo kính bảo vệ khi ra ngoài.',
'Vệ sinh mắt bằng nước muối sinh lý, thuốc nhỏ mắt kháng sinh nếu vi khuẩn, thuốc chống dị ứng nếu dị ứng. Virus thường tự khỏi 1-2 tuần. Tránh làm lây lan cho người khác.'),

('D010', 'Bệnh Tiêu chảy cấp',
'Tình trạng đi ngoài phân lỏng nhiều lần, kéo dài dưới 14 ngày. Bệnh thường do nhiễm trùng đường tiêu hóa, có thể gây mất nước nghiêm trọng, đặc biệt ở trẻ em và người già.',
'Đi ngoài phân lỏng hoặc nước nhiều lần/ngày, đau quặn bụng, nôn, sốt, mệt mỏi, khát nước, môi khô, mắt trũng, tiểu ít.',
'Nguyên nhân: virus (Rotavirus, Norovirus), vi khuẩn (E. coli, Salmonella, Shigella, Vibrio cholerae), ký sinh trùng (Giardia), ăn uống không hợp vệ sinh, nguồn nước ô nhiễm.',
'Ăn chín, uống sôi, rửa tay trước và sau khi đi vệ sinh, dùng nước sạch, xử lý phân an toàn, tiêm vắc-xin (Rotavirus, tả) cho trẻ.',
'Điều trị chủ yếu bù nước và điện giải (Oresol, dung dịch uống), duy trì ăn uống thức ăn mềm/dễ tiêu. Thuốc chống tiêu chảy chỉ dùng khi cần theo chỉ định. Theo dõi biến chứng mất nước.'),

('D011', 'Viêm dạ dày ruột',
'Viêm dạ dày ruột là tình trạng viêm niêm mạc dạ dày và ruột non, thường gọi là “cúm dạ dày”. Bệnh gây rối loạn tiêu hóa đột ngột và có thể lây lan trong cộng đồng.',
'Nôn, buồn nôn, tiêu chảy đột ngột, đau quặn bụng, sốt nhẹ, ớn lạnh, mệt mỏi, mất nước nếu nặng.',
'Nguyên nhân chủ yếu do virus (Norovirus, Rotavirus), vi khuẩn (Salmonella, E. coli, Campylobacter) từ thực phẩm/nước uống bị ô nhiễm.',
'Rửa tay kỹ, bảo quản và chế biến thực phẩm an toàn, ăn chín uống sôi, tách riêng đồ sống và chín, vệ sinh môi trường.',
'Bệnh thường tự khỏi. Bù nước và điện giải, nghỉ ngơi, ăn thức ăn nhạt, mềm khi triệu chứng giảm. Thuốc chống nôn hoặc chống tiêu chảy theo chỉ định bác sĩ nếu cần.'),

('D012', 'Thủy đậu',
'Thủy đậu là bệnh truyền nhiễm cấp tính do virus Varicella-Zoster gây ra, lây lan mạnh, chủ yếu ở trẻ em. Bệnh gây phát ban phỏng nước ngứa và sốt nhẹ.',
'Sốt nhẹ, mệt mỏi, chán ăn, xuất hiện nốt đỏ -> nốt phỏng nước -> vỡ đóng vảy, mọc khắp cơ thể, ngứa nhiều.',
'Virus Varicella-Zoster lây qua đường hô hấp hoặc tiếp xúc trực tiếp với dịch phỏng nước.',
'Tiêm vắc-xin phòng thủy đậu, cách ly người bệnh, tránh tiếp xúc với dịch phỏng, giữ vệ sinh cá nhân.',
'Điều trị triệu chứng: hạ sốt (Paracetamol), bôi dung dịch sát khuẩn (xanh methylen) lên nốt phỏng vỡ, giữ vệ sinh da, cắt móng tay tránh gãi. Tránh biến chứng nhiễm trùng thứ cấp.'),

('D013', 'Bệnh Tăng huyết áp',
'Tăng huyết áp là tình trạng áp lực máu trong động mạch cao hơn bình thường kéo dài, có thể gây biến chứng tim mạch, đột quỵ, thận mạn tính. Bệnh thường không có triệu chứng rõ ràng, nên được gọi là “kẻ giết người thầm lặng”.',
'Thường không triệu chứng rõ. Một số người bị đau đầu, chóng mặt, ù tai, hoa mắt, chảy máu cam, mệt mỏi, tim đập nhanh.',
'Nguyên nhân: phần lớn vô căn (nguyên phát). Yếu tố nguy cơ: tuổi cao, di truyền, thừa cân, béo phì, ăn mặn, hút thuốc, uống rượu, stress, lười vận động.',
'Giảm cân, chế độ ăn ít muối, tăng rau xanh, tập thể dục đều, không hút thuốc, hạn chế rượu, kiểm soát căng thẳng.',
'Thay đổi lối sống. Thuốc hạ huyết áp: lợi tiểu, chẹn beta, ức chế men chuyển theo chỉ định. Theo dõi huyết áp thường xuyên.'),

('D014', 'Bệnh Tim mạch vành',
'Bệnh tim mạch vành xảy ra khi động mạch nuôi tim bị hẹp hoặc tắc do mảng xơ vữa, làm giảm lưu lượng máu cơ tim, gây đau thắt ngực, nhồi máu cơ tim, suy tim.',
'Đau thắt ngực (cảm giác đè, siết chặt), lan ra cánh tay, vai, cổ, khó thở, mệt mỏi, tim đập nhanh, hồi hộp, buồn nôn. Nặng nhất là nhồi máu cơ tim.',
'Nguyên nhân: xơ vữa động mạch, tăng huyết áp, rối loạn mỡ máu, đái tháo đường, hút thuốc, béo phì, di truyền.',
'Kiểm soát huyết áp, mỡ máu, đường huyết, chế độ ăn lành mạnh (ít béo bão hòa, ít muối), không hút thuốc, tập thể dục đều, duy trì cân nặng hợp lý.',
'Thay đổi lối sống. Thuốc: giãn mạch, giảm mỡ, chống đông. Can thiệp: nong mạch, đặt stent hoặc phẫu thuật bắc cầu nếu cần. Theo dõi định kỳ và phòng biến chứng.'),

('D015', 'Đái tháo đường',
'Đái tháo đường là bệnh rối loạn chuyển hóa mạn tính, đặc trưng bởi đường huyết luôn cao, gây tổn thương mạch máu, thần kinh và các cơ quan khác. Type 1 thường xuất hiện ở trẻ em/tuổi vị thành niên, Type 2 ở người lớn.',
'Type 1: ăn nhiều, uống nhiều, tiểu nhiều, gầy sút cân nhanh, mệt mỏi, mờ mắt, vết thương lâu lành, nhiễm trùng da. Type 2 thường âm thầm, có thể đau đầu, mệt mỏi, vết thương lâu lành.',
'Nguyên nhân: Type 1 do tự miễn, tụy không sản xuất insulin. Type 2: kháng insulin, lối sống kém lành mạnh, béo phì, di truyền.',
'Type 2: duy trì cân nặng hợp lý, chế độ ăn giảm đường, tăng chất xơ, tập thể dục đều, không hút thuốc.',
'Type 1: tiêm insulin. Type 2: thay đổi lối sống, thuốc uống hạ đường huyết, có thể tiêm insulin. Theo dõi đường huyết định kỳ, khám sức khỏe định kỳ.'),

('D016', 'Ung thư',
'Ung thư là nhóm bệnh do tế bào bất thường phát triển không kiểm soát, xâm lấn và phá hủy mô, có khả năng di căn. Có nhiều loại: ung thư vú, phổi, gan, dạ dày, ruột, máu, …',
'Sụt cân không rõ nguyên nhân, mệt mỏi, sốt kéo dài, thay đổi thói quen đại/tiểu tiện, vết loét không lành, ho dai dẳng, xuất huyết bất thường, nổi u cục, đau vùng bị tổn thương.',
'Đột biến gen, di truyền, hút thuốc, uống rượu, phơi nhiễm hóa chất/bức xạ, béo phì, nhiễm virus (HPV, viêm gan B/C).',
'Không hút thuốc, hạn chế rượu, ăn uống lành mạnh, tập thể dục, duy trì cân nặng, tiêm vắc-xin phòng HPV/viêm gan B, tầm soát ung thư định kỳ.',
'Điều trị tùy loại và giai đoạn: phẫu thuật loại bỏ khối u, xạ trị, hóa trị, liệu pháp miễn dịch, theo dõi lâu dài. Kết hợp chăm sóc giảm nhẹ, dinh dưỡng và hỗ trợ tâm lý.'),

('D017', 'Bệnh Phổi tắc nghẽn mạn tính (COPD)',
'COPD là bệnh mạn tính gây tắc nghẽn luồng khí ra vào phổi, gồm viêm phế quản mạn và khí phế thũng. Bệnh tiến triển từ từ, làm giảm khả năng hô hấp và chất lượng cuộc sống.',
'Khó thở, đặc biệt khi gắng sức, ho mạn tính, khạc đờm, thở khò khè, mệt mỏi, sụt cân, tái xanh môi/nail (nếu nặng), dễ nhiễm trùng hô hấp.',
'Nguyên nhân: hút thuốc lá (chủ yếu), khói bụi nghề nghiệp, ô nhiễm không khí, viêm nhiễm phổi tái phát.',
'Ngưng hút thuốc hoàn toàn, tránh môi trường ô nhiễm, tiêm vắc-xin cúm và phế cầu hàng năm, tập thể dục nhẹ nhàng.',
'Không thể chữa khỏi hoàn toàn. Dùng thuốc giãn phế quản, corticosteroid dạng hít, liệu pháp oxy, phục hồi chức năng hô hấp. Theo dõi định kỳ, tránh nhiễm trùng hô hấp.'),

('D018', 'Viêm loét dạ dày và Tá tràng',
'Viêm loét dạ dày-tá tràng là tình trạng tổn thương niêm mạc do acid và pepsin gây ra, dẫn đến đau thượng vị, khó tiêu, có thể xuất huyết tiêu hóa. Bệnh liên quan đến Helicobacter pylori và lối sống.',
'Đau vùng thượng vị, đau khi đói hoặc sau ăn, ợ hơi, ợ chua, buồn nôn, nôn, đầy bụng, khó tiêu, đôi khi xuất huyết tiêu hóa, nôn máu hoặc đi ngoài phân đen.',
'Nguyên nhân: nhiễm vi khuẩn Helicobacter pylori, lạm dụng NSAIDs, stress, rượu bia, hút thuốc lá, di truyền.',
'Vệ sinh ăn uống, hạn chế rượu bia, thuốc lá, stress, sử dụng NSAIDs thận trọng, điều trị HP khi nhiễm.',
'Thuốc giảm tiết acid (PPI), thuốc trung hòa acid, kháng sinh diệt HP nếu có, thay đổi lối sống, ăn uống đúng giờ, tránh thức ăn cay nóng, theo dõi biến chứng.'),

('D019', 'Bệnh Gút (Gout)',
'Gút là bệnh viêm khớp do rối loạn chuyển hóa acid uric, gây lắng đọng tinh thể urat ở khớp và mô, dẫn đến cơn đau cấp hoặc viêm khớp mạn tính, có thể hình thành hạt tophi.',
'Cơn gút cấp: sưng, nóng, đỏ, đau dữ dội khớp, thường khởi phát ở ngón chân cái, giai đoạn mạn: hạt tophi dưới da, viêm khớp kéo dài, biến dạng khớp, hạn chế vận động.',
'Nguyên nhân: tăng sản xuất hoặc giảm đào thải acid uric. Yếu tố nguy cơ: di truyền, nam giới, tuổi cao, béo phì, ăn nhiều thực phẩm giàu purin, uống nhiều rượu bia.',
'Hạn chế thực phẩm giàu purin, hạn chế bia/rượu, uống nhiều nước, duy trì cân nặng hợp lý, tập thể dục nhẹ nhàng.',
'(Cơn cấp) Thuốc kháng viêm NSAIDs, Colchicine, Corticosteroid. (Mạn tính) Thuốc hạ acid uric máu (Allopurinol, Febuxostat), kết hợp thay đổi lối sống, theo dõi định kỳ chức năng thận và acid uric.'),

('D020', 'Viêm khớp mạn tính',
'Viêm khớp mạn tính là tình trạng viêm kéo dài ở một hoặc nhiều khớp. Gồm 2 loại chính: Thoái hóa khớp (OA) do hao mòn sụn, và Viêm khớp dạng thấp (RA) do tự miễn. Bệnh gây đau, giảm vận động, biến dạng khớp.',
'Đau khớp, cứng khớp buổi sáng (RA), đau tăng khi vận động (OA), sưng khớp, giảm biên độ vận động, biến dạng khớp giai đoạn muộn, mệt mỏi, yếu cơ.',
'Nguyên nhân: OA - tuổi, chấn thương, béo phì. RA - hệ miễn dịch tấn công màng hoạt dịch, di truyền, yếu tố môi trường, nhiễm trùng.',
'Duy trì cân nặng hợp lý, tập thể dục phù hợp, chế độ ăn chống viêm (omega-3, rau xanh), không hút thuốc.',
'Không thể chữa khỏi hoàn toàn. Điều trị giảm đau, kháng viêm (NSAIDs, Corticoid), vật lý trị liệu, RA dùng thuốc cơ bản DMARDs, phẫu thuật thay khớp khi khớp hỏng nặng.');
